### ISSUE TITLE
unable to install this via mise

### ISSUE THREAD

**Issue by drewwells** [Dabolus/asdf-tmux#9]
**Describe the bug**

build is complaining about curses

**Steps to reproduce**

```
~ ❯ mise plugin i tmux https://github.com/Dabolus/asdf-tmux
~ ❯ mise use -g tmux -f
...
configure: error: "curses not found"
make: *** No targets specified and no makefile found.  Stop.
asdf-tmux: An error occurred while installing tmux 3.5a.
mise ERROR Failed to install tmux@3.5a
mise ERROR ~/.local/share/mise/plugins/tmux/bin/install exited with non-zero status: exit code 1
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

**Expected behavior**

tmux is installed

**Screenshots**

**Additional context**

**Comment by drewwells** [comment]
Resolved this on Ubuntu by installing libncurses. Maybe the dependencies need to be updated.
```
sudo apt-get install libncurses5-dev libncursesw5-dev
```

**Comment by Dabolus** [comment]
Hi, thanks for discovering and debugging the issue. I can confirm ncurses is a dependency, as stated on [tmux wiki](https://github.com/tmux/tmux/wiki/Installing#from-source-tarball).

I personally never noticed it because I always used it on Mac, where ncurses is preinstalled. 

For now, I added [a note about this to the readme](https://github.com/Dabolus/asdf-tmux/commit/f405ff0540f46292cd7118809218d1d9b6d4c379), but I will try to see if I'm able to download `ncurses` automatically on installation, as already did with `libevent`, for a more streamlined installation also on other platforms.

By the way, thanks for introducing me to mise 😄
